leftnav:
- identifier: 708ca5b9-7466-493d-8875-b8464dd11d87
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 6181f96e-9626-4b87-b9aa-75111f8f1ff2
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: e5fb600c-2151-49c5-8f85-166a460c6ce9
  name: Lecture Videos
  pageRef: /video_galleries/this-page-presents-prerecorded-lecture-videos-that-were-viewed-by-the-students-in-11165-urban-energy-systems-and-policy
  weight: 30
- identifier: 5fed9bbb-3091-425f-bbf9-f7793ca18270
  name: Lecture Slides
  pageRef: /pages/lecture-videos
  weight: 40
- identifier: d65833b2-459f-409e-9fe4-0685952897a2
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
